export interface TraderMission {
  id: string;
  dia: number;
  semana: number;
  trimestre: number;
  titulo: string;
  objetivo: string;
  reto: string;
  porQueFunciona: string;
  aplicacionCotidiana: string;
  categoria: string;
}

export const TRADER_MISSIONS: TraderMission[] = [
  {
    id: "1",
    dia: 1,
    semana: 1,
    trimestre: 1,
    titulo: "El ritual del reset",
    objetivo: "Desvincular la identidad de los errores pasados",
    reto: "Escribe tu peor error de trading en un papel. Quémalo o rómpelo mientras dices: 'No soy mis errores, soy mi evolución'. Guarda las cenizas/trozos en un sobre etiquetado 'Lección 1'",
    porQueFunciona: "Acto físico de liberación que desvincula identidad de resultados. El cerebro procesa actos simbólicos como cierres emocionales reales.",
    aplicacionCotidiana: "Aplica este reset ante cualquier error fuera del trading hoy.",
    categoria: "Dominio Emocional",
  },
  {
    id: "2",
    dia: 2,
    semana: 1,
    trimestre: 1,
    titulo: "La caja de Pandora emocional",
    objetivo: "Identificar patrones emocionales dominantes",
    reto: "Consigue una caja pequeña. Cada emoción fuerte del día (miedo, euforia, rabia) escríbela en un papel y métela dentro. Al finalizar el día: abre, lee e identifica el patrón dominante.",
    porQueFunciona: "Externalizar emociones crea distancia y perspectiva. Lo que se nombra y se toca pierde su poder de control inconsciente.",
    aplicacionCotidiana: "Hazlo con las tensiones domésticas o sociales.",
    categoria: "Dominio Emocional",
  },
  {
    id: "3",
    dia: 3,
    semana: 1,
    trimestre: 1,
    titulo: "Camina tu pérdida",
    objetivo: "Resetear el sistema nervioso ante la frustración",
    reto: "Por cada % perdido hoy camina 10 minutos. Sin móvil, sin música, solo observación. Anota qué pensamiento recurrente apareció durante la caminata.",
    porQueFunciona: "Desvincula la reacción impulsiva. El movimiento físico bilateral procesa el trauma de la pérdida y reduce el cortisol.",
    aplicacionCotidiana: "Camina ante cualquier momento de estrés hoy.",
    categoria: "Dominio Emocional",
  },
  {
    id: "4",
    dia: 4,
    semana: 1,
    trimestre: 1,
    titulo: "El espejo del trader",
    objetivo: "Activar la honestidad radical",
    reto: "Antes de operar, mírate al espejo 30 segundos y pregunta: '¿Opero desde mi sistema o desde mi necesidad?'. Si dudas o sientes ansiedad, hoy no operas.",
    porQueFunciona: "La confrontación física con uno mismo activa la corteza prefrontal y reduce la impulsividad del sistema límbico.",
    aplicacionCotidiana: "Mírate al espejo antes de tomar una decisión importante.",
    categoria: "Dominio Emocional",
  },
  {
    id: "5",
    dia: 5,
    semana: 1,
    trimestre: 1,
    titulo: "Silencio productivo",
    objetivo: "Procesar la jornada sin estímulos digitales",
    reto: "30 minutos post-mercado sin pantallas. Solo papel y boli: escribe 3 aciertos y 3 mejoras. Dobla el papel y guárdalo sin releerlo.",
    porQueFunciona: "El cerebro consolida aprendizajes mucho mejor en ausencia de estímulos. El papel ancla la lección de forma táctil.",
    aplicacionCotidiana: "30 minutos de desconexión total antes de dormir.",
    categoria: "Dominio Emocional",
  },
  {
    id: "6",
    dia: 6,
    semana: 1,
    trimestre: 1,
    titulo: "La moneda de la pausa",
    objetivo: "Romper la automatización impulsiva",
    reto: "Ten una moneda especial en tu escritorio. Antes de cada entrada: lánzala y espera 10 segundos mientras cae. No decide nada, solo crea espacio entre el impulso y el clic.",
    porQueFunciona: "Crea una interrupción física del patrón impulsivo. Te devuelve el control consciente sobre el acto de operar.",
    aplicacionCotidiana: "Espera 10 segundos antes de responder un mensaje difícil.",
    categoria: "Dominio Emocional",
  },
  {
    id: "7",
    dia: 7,
    semana: 1,
    trimestre: 1,
    titulo: "Inventario semanal",
    objetivo: "Discernir entre ego y sistema",
    reto: "Saca todos los papeles de la semana. Clasifícalos en 3 montones: 'Ego', 'Sistema' y 'Aprendizaje'. Quema solemnemente solo los de la pila 'Ego'.",
    porQueFunciona: "La clasificación refuerza la capacidad analítica sobre la emocional. El ritual de quema simboliza el descarte de patrones tóxicos.",
    aplicacionCotidiana: "Haz un inventario de tus quejas de la semana y descarta las innecesarias.",
    categoria: "Dominio Emocional",
  },
  {
    id: "8",
    dia: 8,
    semana: 2,
    trimestre: 1,
    titulo: "El contrato de sangre",
    objetivo: "Aumentar el compromiso con el plan",
    reto: "Escribe tu plan de trading a mano con letra grande y fírmalo solemnemente. Pon una gota de tu perfume o colonia en el papel. Cuélgalo donde lo veas antes de encender la pantalla.",
    porQueFunciona: "El compromiso escrito y firmado aumenta drásticamente la probabilidad de cumplimiento. El olfato ancla la disciplina al sistema límbico.",
    aplicacionCotidiana: "Haz un contrato contigo para una meta de salud.",
    categoria: "Anclajes de Disciplina",
  },
  {
    id: "9",
    dia: 9,
    semana: 2,
    trimestre: 1,
    titulo: "El frasco de la constancia",
    objetivo: "Valorar el proceso sobre el resultado",
    reto: "Consigue un frasco transparente. Cada día que sigues tu plan al pie de la letra, mete una piedra o canica. No importa si ganaste o perdiste dinero, solo si fuiste disciplinado.",
    porQueFunciona: "Proporciona evidencia física y visual de consistencia. Desvía el foco del dinero (variable) al comportamiento (controlable).",
    aplicacionCotidiana: "Usa un frasco para cualquier hábito que quieras crear.",
    categoria: "Anclajes de Disciplina",
  },
  {
    id: "10",
    dia: 10,
    semana: 2,
    trimestre: 1,
    titulo: "Desayuno ritual",
    objetivo: "Crear previsibilidad en el entorno",
    reto: "Come exactamente lo mismo cada día de trading durante esta semana. Antes del primer bocado di: 'Hoy soy disciplina'.",
    porQueFunciona: "La rutina reduce la fatiga de decisión. Un entorno predecible predispone a una ejecución predecible y disciplinada.",
    aplicacionCotidiana: "Crea una rutina matutina idéntica para toda la semana.",
    categoria: "Anclajes de Disciplina",
  },
  {
    id: "11",
    dia: 11,
    semana: 2,
    trimestre: 1,
    titulo: "La alarma del ego",
    objetivo: "Mantener la presencia consciente",
    reto: "Pon 3 alarmas aleatorias durante tu sesión. Cuando suene pregúntate: '¿Estoy en mi plan o en mi cabeza?'. Anota la respuesta en un post-it y pégalo en el marco de tu pantalla.",
    porQueFunciona: "Interrumpe el estado de 'trance' que a veces induce el mercado. Te obliga a re-evaluar tu estado mental actual.",
    aplicacionCotidiana: "Pon alarmas para chequear tu postura o respiración hoy.",
    categoria: "Anclajes de Disciplina",
  },
  {
    id: "12",
    dia: 12,
    semana: 2,
    trimestre: 1,
    titulo: "El objeto guardián",
    objetivo: "Anclar la conducta a un objeto físico",
    reto: "Elige un objeto pequeño (piedra, moneda, figura). Sujétalo firmemente cada vez ANTES de abrir una operación. Solo tienes permiso para operar si tocaste el objeto primero.",
    porQueFunciona: "Crea un disparador físico de conciencia. El tacto interrumpe la impulsividad visual de los gráficos.",
    aplicacionCotidiana: "Toca un objeto específico antes de entrar a casa para dejar el estrés fuera.",
    categoria: "Anclajes de Disciplina",
  },
  {
    id: "13",
    dia: 13,
    semana: 2,
    trimestre: 1,
    titulo: "Carta a tu yo impulsivo",
    objetivo: "Externalizar y desarmar el autosabotaje",
    reto: "Escribe una carta a tu 'yo que quiere vengarse del mercado'. Explícale por qué no va a operar hoy por fuera del plan. Guárdala en un sobre que diga: 'Leer en días rojos'.",
    porQueFunciona: "Hacer consciente lo inconsciente le quita poder. Tratar al impulso como una entidad separada facilita su gestión.",
    aplicacionCotidiana: "Escribe a tu yo perezoso cuando no quieras ir al gimnasio.",
    categoria: "Anclajes de Disciplina",
  },
  {
    id: "14",
    dia: 14,
    semana: 2,
    trimestre: 1,
    titulo: "Ritual de cierre semanal",
    objetivo: "Cerrar ciclos y limpiar tensiones",
    reto: "Lávate las manos con agua muy fría al terminar tu última sesión de la semana. Mientras lo haces di: 'El mercado se queda en el mercado'. Sécalas con una toalla específica solo para esto.",
    porQueFunciona: "El agua fría activa el sistema parasimpático. El ritual simboliza la limpieza de las emociones acumuladas para proteger tu vida personal.",
    aplicacionCotidiana: "Crea un ritual de cierre para tu jornada laboral general.",
    categoria: "Anclajes de Disciplina",
  },
  {
    id: "15",
    dia: 15,
    semana: 3,
    trimestre: 1,
    titulo: "La línea de tu vida trader",
    objetivo: "Combatir la miopía del corto plazo",
    reto: "En una hoja grande dibuja una línea horizontal. Marca dónde empezaste, dónde estás hoy y hacia dónde vas. Pégala horizontalmente en la pared frente a ti.",
    porQueFunciona: "Proporciona perspectiva histórica. Ayuda a recordar que el éxito es un maratón, no un sprint de un solo día.",
    aplicacionCotidiana: "Dibuja tu línea de vida personal para relativizar problemas actuales.",
    categoria: "Perspectiva Temporal",
  },
  {
    id: "16",
    dia: 16,
    semana: 3,
    trimestre: 1,
    titulo: "Escribe a tu yo del futuro",
    objetivo: "Anclar el propósito a largo plazo",
    reto: "Escribe una carta a ti mismo dentro de 1 año. ¿Qué trader eres? ¿Qué superaste? Guárdala en un sobre sellado con fecha de apertura para dentro de 12 meses.",
    porQueFunciona: "Crea una conexión emocional con tus objetivos futuros. Facilita el sacrificio de la gratificación inmediata de hoy.",
    aplicacionCotidiana: "Hazlo para cualquier proyecto vital que tengas.",
    categoria: "Perspectiva Temporal",
  },
  {
    id: "17",
    dia: 17,
    semana: 3,
    trimestre: 1,
    titulo: "El álbum de versiones",
    objetivo: "Visualizar el progreso evolutivo",
    reto: "Dibuja o busca 3 imágenes: Tu yo principiante, tu yo presente y tu yo maestro. Ponlas en secuencia visible en tu oficina.",
    porQueFunciona: "Refuerza la identidad del 'Trader en Proceso'. La visualización de la maestría futura motiva la disciplina presente.",
    aplicacionCotidiana: "Visualiza tus versiones en cualquier habilidad que estés aprendiendo.",
    categoria: "Perspectiva Temporal",
  },
  {
    id: "18",
    dia: 18,
    semana: 3,
    trimestre: 1,
    titulo: "Medición sin números",
    objetivo: "Valorar el crecimiento cualitativo",
    reto: "Describe tu evolución de este mes SIN mencionar dinero ni porcentajes. Usa frases como: 'Ahora soy más calmado cuando...' o 'Ya no reacciono ante...'.",
    porQueFunciona: "El dinero es un resultado retardado. Las métricas de comportamiento son indicadores adelantados del éxito futuro.",
    aplicacionCotidiana: "Mide tu progreso en tus relaciones sin usar frecuencia.",
    categoria: "Perspectiva Temporal",
  },
  {
    id: "19",
    dia: 19,
    semana: 3,
    trimestre: 1,
    titulo: "La foto del primer día",
    objetivo: "Honrar el camino recorrido",
    reto: "Hazte una foto hoy o busca una de cuando empezaste. Escribe atrás: 'Empecé aquí, no vuelvo atrás'. Mírala cada vez que dudes de tu capacidad.",
    porQueFunciona: "El anclaje visual a un punto de partida evita el retroceso. Refuerza el compromiso de no desperdiciar el esfuerzo ya invertido.",
    aplicacionCotidiana: "Conserva una foto de tus inicios en cualquier gran reto.",
    categoria: "Perspectiva Temporal",
  },
  {
    id: "20",
    dia: 20,
    semana: 3,
    trimestre: 1,
    titulo: "Proyección mensual",
    objetivo: "Crear una representación física de la racha",
    reto: "En 30 post-its escribe: 'Día X: Soy constancia'. Pega uno cada día que completes tu rutina completa. Al final del mes verás tu mural de disciplina.",
    porQueFunciona: "La visualización de la 'racha' crea una aversión psicológica a romperla. Convierte la disciplina abstracta en algo físico y creciente.",
    aplicacionCotidiana: "Usa post-its para cualquier racha de salud.",
    categoria: "Perspectiva Temporal",
  },
  {
    id: "21",
    dia: 21,
    semana: 3,
    trimestre: 1,
    titulo: "El ritual de la gratitud trader",
    objetivo: "Enfocar la mente en el aprendizaje",
    reto: "Escribe 3 cosas que el mercado te enseñó esta semana sobre TI mismo (no de técnica). Dóblalas y mételas en un sobre que diga 'Gracias'.",
    porQueFunciona: "Cambia el foco de 'pérdida de dinero' a 'compra de lección'. Reduce el resentimiento hacia el mercado y fomenta la objetividad.",
    aplicacionCotidiana: "Agradece un aprendizaje de cada conflicto hoy.",
    categoria: "Perspectiva Temporal",
  },
  {
    id: "22",
    dia: 22,
    semana: 4,
    trimestre: 1,
    titulo: "La silla del enemigo",
    objetivo: "Confrontar la sombra del trader",
    reto: "Pon una silla vacía frente a ti. Siéntate e imagina a tu 'yo impulsivo' sentado ahí. Dile en voz alta y firme por qué no va a sabotearte hoy.",
    porQueFunciona: "Técnica de la silla vacía (Gestalt). Permite integrar y dialogar con partes conflictivas de la personalidad para neutralizarlas.",
    aplicacionCotidiana: "Habla con tu yo procrastinador frente a una silla vacía.",
    categoria: "Protección Mental",
  },
  {
    id: "23",
    dia: 23,
    semana: 4,
    trimestre: 1,
    titulo: "El diario manchado",
    objetivo: "Transformar el error en abono",
    reto: "Escribe tu peor momento del día en papel. Mójalo bajo el grifo. Mientras se seca medita: '¿Qué me enseña esto?'. Cuando esté seco, escribe encima de la mancha la lección aprendida.",
    porQueFunciona: "Metáfora física de resiliencia. El error (la mancha) se convierte en la base sobre la que se construye el conocimiento.",
    aplicacionCotidiana: "Anota un error del pasado y escribe tu aprendizaje encima.",
    categoria: "Protección Mental",
  },
  {
    id: "24",
    dia: 24,
    semana: 4,
    trimestre: 1,
    titulo: "Limpieza de espacio",
    objetivo: "Reducir el ruido mental externo",
    reto: "Limpia físicamente tu zona de trading. Retira todo lo que no sea esencial. Deja solo: tu objeto guardián, tu contrato y tu frasco.",
    porQueFunciona: "Un entorno desordenado genera carga cognitiva. El minimalismo externo facilita el enfoque y la calma interna necesaria para decidir.",
    aplicacionCotidiana: "Limpia un cajón o superficie de tu casa hoy.",
    categoria: "Protección Mental",
  },
  {
    id: "25",
    dia: 25,
    semana: 4,
    trimestre: 1,
    titulo: "El papel de la venganza",
    objetivo: "Hacer consciente lo absurdo del impulso",
    reto: "Si sientes ganas de 'recuperar' una pérdida, escribe: 'Quiero vengarme porque...' y completa 10 razones. Léelas en voz alta y luego rompe el papel.",
    porQueFunciona: "Ver el impulso de venganza escrito revela su irracionalidad. Leerlo en voz alta activa el juicio crítico y desarma la emoción.",
    aplicacionCotidiana: "Escribe por qué quieres tener la última palabra en una discusión.",
    categoria: "Protección Mental",
  },
  {
    id: "26",
    dia: 26,
    semana: 4,
    trimestre: 1,
    titulo: "Meditación del trader",
    objetivo: "Entrenar la observación sin juicio",
    reto: "10 minutos sentado en silencio observando tu respiración. Cuando aparezca el pensamiento 'debo operar', etiquétalo como 'pensamiento' y vuelve al aire.",
    porQueFunciona: "Entrena la capacidad de notar un impulso sin tener que actuar sobre él. Desarrolla la 'pausa' necesaria para el trading profesional.",
    aplicacionCotidiana: "Observa tus ganas de mirar el móvil sin hacerlo.",
    categoria: "Protección Mental",
  },
  {
    id: "27",
    dia: 27,
    semana: 4,
    trimestre: 1,
    titulo: "El ejercicio de la pérdida",
    objetivo: "Anticipar y neutralizar el dolor",
    reto: "Simula en papel una pérdida de tu stop loss máximo. Escribe qué sentirías y qué harías (seguir el plan). Ahora ya estás emocionalmente preparado si sucede.",
    porQueFunciona: "Pre-exposición emocional. Reduce el impacto del shock cuando la pérdida ocurre, permitiendo una respuesta racional y no defensiva.",
    aplicacionCotidiana: "Imagina un pequeño contratiempo y planifica tu calma.",
    categoria: "Protección Mental",
  },
  {
    id: "28",
    dia: 28,
    semana: 4,
    trimestre: 1,
    titulo: "El cierre mensual",
    objetivo: "Hacer balance y purga",
    reto: "Clasifica tus papeles del mes en: 'Me construyó' y 'Me distrajo'. Guarda solemnemente los primeros y quema o destruye los segundos.",
    porQueFunciona: "Refuerza la memoria selectiva hacia lo positivo y lo útil. El ritual de descarte libera el peso emocional acumulado durante el mes.",
    aplicacionCotidiana: "Haz limpieza de archivos o correos antiguos hoy.",
    categoria: "Protección Mental",
  },
  {
    id: "29",
    dia: 29,
    semana: 5,
    trimestre: 1,
    titulo: "El mapa del mes",
    objetivo: "Identificar patrones de comportamiento",
    reto: "Dibuja un camino de 30 casillas. Verde = día disciplinado, Rojo = día impulsivo. ¿Qué patrón ves? ¿Hay días de la semana más difíciles?",
    porQueFunciona: "Análisis visual de datos conductuales. Permite identificar disparadores temporales o situacionales de la falta de disciplina.",
    aplicacionCotidiana: "Haz un mapa de tus niveles de energía este mes.",
    categoria: "Integración",
  },
  {
    id: "30",
    dia: 30,
    semana: 5,
    trimestre: 1,
    titulo: "Carta de perdón",
    objetivo: "Eliminar la culpa que sabotea",
    reto: "Escríbete una carta perdonándote por cada error del mes. 'Me perdono por... porque estoy aprendiendo'. Guárdala en tu cuaderno de evolución.",
    porQueFunciona: "La culpa induce el castigo inconsciente (perder más). El perdón restaura la auto-eficacia y permite volver a operar con la mente limpia.",
    aplicacionCotidiana: "Perdónate por algo que no hiciste perfecto hoy.",
    categoria: "Integración",
  },
  {
    id: "31",
    dia: 31,
    semana: 5,
    trimestre: 1,
    titulo: "El ritual de renovación",
    objetivo: "Marcar un nuevo comienzo",
    reto: "Vacía tu frasco de constancia en un recipiente mayor etiquetado 'MES 1'. Limpia el frasco y di: 'Mes 1 completo. Soy constancia, no motivación'.",
    porQueFunciona: "Crea una distinción psicológica entre el pasado y el futuro. La acumulación física de piedras es el trofeo real del trader profesional.",
    aplicacionCotidiana: "Celebra el fin de un mes con una cena especial.",
    categoria: "Integración",
  }
];

export const getMissionByDay = (day: number): TraderMission | undefined => {
  return TRADER_MISSIONS.find((m) => m.dia === day);
};

export const getMissionsByWeek = (week: number): TraderMission[] => {
  return TRADER_MISSIONS.filter((m) => m.semana === week);
};

export const getMissionsByTrimester = (trimester: number): TraderMission[] => {
  return TRADER_MISSIONS.filter((m) => m.trimestre === trimester);
};

export const getTotalMissions = (): number => {
  return TRADER_MISSIONS.length;
};
